<a href="https://colab.research.google.com/github/mario-i-caicedo-ai/Relatividad/blob/main/%C3%81lgebra_de_Lorentz_so(3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Representaciones fundamentales de $so(3)$ y $so(1,3)$.

## Objetivo del cuaderno: 

* Discutir aspectos elementales de ambas álgebras.

In [1]:
import numpy as np

In [2]:
def conmutador(A,B):
  C=np.dot(A,B)-np.dot(B,A)
  return C

--------------------------------------------------------------

## A manera de recordatorio:

$su(2)$:

$$
[\mathbf{s}_{i},\mathbf{s}_{j}]=i\epsilon_{ijk}\mathbf{s}_{k}$$

## Generadores del grupo $SO(3)$

* **Comentarios**
  * Recuerde que podemos definir $SO(3)$ como el conjunto de matrices $3\times{}3$ que conservan la métrica euclídea,
    $$\mathbf{M}^T\mathbf{g}\mathbf{T}=\mathbf{g},\quad{}\mathbf{g}=diag(+,+,+)$$.
    * Escriba un elemento del grupo $SO(3)$ cercano a la identidad $$\mathbf{R}=\mathbf{I}+\boldsymbol{\epsilon}$$ e imponga la condición definitoria del grupo sobre $\mathbf{R}$.
    * Obtendrá los generadores $\mathbf{M}_i$, $i=1,2,3$ definidos a continuación  


*$$\mathbf{M}_{1}=\begin{pmatrix}0&0&0\\0&0&1\\0&-1&0\end{pmatrix}\,,\quad\mathbf{M}_{2}=\begin{pmatrix}0&0&-1\\0&0&0\\1&0&0\end{pmatrix}\,,\quad\mathbf{M}_{3}=\begin{pmatrix}0&1&0\\-1&0&0\\0&0&0\end{pmatrix}$$


* $\mathbf{M}_{3}$ genera rotaciónes alrededor del eje $z$
* **Ejercicio** Interprete el signifcado de los otros generadores


## Preparación de los generadores

In [3]:
# Este paso no es muy importante en este cuaderno en particular.
# De todas maneras, debe correr la celda.
T12=np.matrix("0.,1.,0.;-1.,0.,0.;0.,0.,0.")
T23=np.matrix("0.,0.,0.;0.,0.,1.;0.,-1.,0.")
T31=np.matrix("0.,0.,-1.;0.,0.,0;1.,0.,0.")

In [4]:
M1=T23
M2=T31
M3=T12

### La siguiente celda despliega los generadores para su verificación

In [5]:
#
# Comparando con los bloques espaciales de los generadores de la sección 11.7 de J.D. Jackson (segunda edición)
#
print('M1' ,M1) #-S_1
print()
print('M2' ,M2) #-S_2
print()
print('M3' ,M3) #-S_3

M1 [[ 0.  0.  0.]
 [ 0.  0.  1.]
 [ 0. -1.  0.]]

M2 [[ 0.  0. -1.]
 [ 0.  0.  0.]
 [ 1.  0.  0.]]

M3 [[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  0.]]


## Los generadores (reales) $\mathbf{M}_i$ satisfacen el álgebra

$$[\mathbf{M}_{i},\mathbf{M}_{j}]=-\epsilon_{ijk}\mathbf{J}_{k}$$

### Verificación del álgebra

In [6]:
A=conmutador(M1,M2)
B=conmutador(M2,M3)
C=conmutador(M3,M1)

print(A+M3)

print(B+M1)

print(C+M2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Generadores Hermíticos
* $\mathbf{J}_{i}\rightarrow{}-i\mathbf{M}_{i}$
* Álgebra
$$[\mathbf{J}_{i},\mathbf{J}_{j}]=i\epsilon_{ijk}\mathbf{J}_{k}$$
* $so(3)$ es isomorfa al álgebra $su(2)$

* Generadores hermíticos ($\mathbf{J}_i$) en forma explícita


*$$\begin{split}
\mathbf{J}_{1}=-i\begin{pmatrix}0&0&0\\0&0&1\\0&-1&0\end{pmatrix}=&\begin{pmatrix}0&0&0\\0&0&-i\\0&i&0\end{pmatrix}\,,\quad\mathbf{J}_{2}=-i\begin{pmatrix}0&0&-1\\0&0&0\\1&0&0\end{pmatrix}=\begin{pmatrix}0&0&i\\0&0&0\\-i&0&0\end{pmatrix}\\
%
\mathbf{J}_{3}&=-i\begin{pmatrix}0&1&0\\-1&0&0\\0&0&0\end{pmatrix}=\begin{pmatrix}0&-i&0\\i&0&0\\0&0&0\end{pmatrix}
\end{split}$$


## Definición de los generadores hermíticos.

In [7]:
J1=-1.j*M1
J2=-1.j*M2
J3=-1.j*M3

## Despliegue

In [8]:

print('J1 ',J1)
print()
print('J2 ',J2)
print()
print('J3 ',J3)

J1  [[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.-1.j]
 [0.+0.j 0.+1.j 0.+0.j]]

J2  [[0.+0.j 0.+0.j 0.+1.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.-1.j 0.+0.j 0.+0.j]]

J3  [[0.+0.j 0.-1.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


* Verificación del álgebra

In [9]:
A=conmutador(J1,J2)
B=conmutador(J2,J3)
C=conmutador(J3,J1)

In [10]:
print(A-1.j*(J3))
print()
print(B-1.j*J1)
print()
print(C-1.j*J2)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


-----------------------------------------------

# Álgebra del grupo de Lorentz

**Comentarios**

* $SO(1,3)$ se define como el grupo de matrices reales $4\times{}4$ que dejan invariante la métrica $\eta=diag(+,-,-,-)$.
* La representación fundamental (**4**) es tetradimensional.
* $dim[SO(1,3)]=6$
* Hay dos conjuntos de generadores, uno se asocia con +boosts+ y el otro con rotaciones.

## Generadores (hermíticos) de los Boosts

* [$\mathbf{J}_{0i}$], $i=1,2,3$
* Luego redefiniremos $\mathbf{K}_{i}=\mathbf{J}_{0i}$

In [11]:
# Como antes, no es necesario que usted entienda esta celda, 
#es solo una preparación interna del programador.
# De todas maneras, debe ejecutarla
J01 = 1.j*np.matrix("0.,1.,0.,0.;1.,0.,0.,0.;0.,0.,0.,0.;0.,0.,0.,0.")
J02 = 1.j*np.matrix("0.,0.,1.,0.;0.,0.,0.,0.;1.,0.,0.,0.;0.,0.,0.,0.")
J03 = 1.j*np.matrix("0.,0.,0.,1.;0.,0.,0.,0.;0.,0.,0.,0.;1.,0.,0.,0.")

$$
\mathbf{J}_{01}=\mathbf{K}_{1}=i\,
%
\begin{pmatrix}
0&1&0&0\\
1&0&0&0\\
0&0&0&0\\
0&0&0&0
\end{pmatrix}\,,
\qquad{}
\mathbf{J}_{02}=\mathbf{K}_{2}=i\,
%
\begin{pmatrix}
0&0&1&0\\
0&0&0&0\\
1&0&0&0\\
0&0&0&0
\end{pmatrix}
\,,\quad{}\mathbf{J}_{03}=\mathbf{K}_{3}=i\,
%
\begin{pmatrix}
0&0&0&1\\
0&0&0&0\\
0&0&0&0\\
1&0&0&0
\end{pmatrix}
$$


In [12]:
print('K1 ',J01)
print()
print('K2 ',J02)
print()
print('K3 ',J03)

K1  [[0.+0.j 0.+1.j 0.+0.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]

K2  [[0.+0.j 0.+0.j 0.+1.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]

K3  [[0.+0.j 0.+0.j 0.+0.j 0.+1.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]]


## Generadores (reales) de las rotaciones

* $\mathbf{N}_{ij}=-\mathbf{N}_{ji}$, $i,j=1,2,3$ son tres en total 
* Luego definiremos nuevos generadores $\mathbf{R}_{i}$  

In [13]:
# Este paso no es fundamental. 
# Debe correr la celda.
N12 = np.matrix("0.,0.,0.,0.;0.,0.,1.,0.;0.,-1.,0.,0.;0.,0.,0.,0.")
N23 = np.matrix("0.,0.,0.,0.;0.,0.,0.,0.;0.,0.,0.,1.;0.,0.,-1.,0.")
N31 = np.matrix("0.,0.,0.,0.;0.,0.,0.,-1.;0.,0.,0.,0.;0.,1.,0.,0.")

In [14]:
# No es necesario ejecutar esta celda.
# Comparación de estas matrices con los generadores 
# espaciales S_i de Jackson, sec 11.7
print('N12 ',N12) # -S_3 
print()
print('N23 ',N23) # -S_1
print()
print('N31 ',N31) # -S2

N12  [[ 0.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  0.  0.]]

N23  [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0. -1.  0.]]

N31  [[ 0.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  0.  0.]
 [ 0.  1.  0.  0.]]


## Definición de los generadores de rotaciones

* $$R_i=\frac{1}{2}\epsilon_{ijk}N_{jk}$$
* $$R_1=N_{23}\,,\quad{}R_2=N_{31}\,,\quad{}R_3=N_{12}$$
* Álgebra:
$$[R_i,R_j]=-\epsilon_{ijk}R_k$$

$$R_1=\begin{pmatrix}0&0&0&0\\0&0&0&0\\0&0&0&-1\\0&0&1&0\end{pmatrix}\,\quad{}R_2=\begin{pmatrix}0&0&0&0\\0&0&0&-1\\0&0&0&0\\0&1&0&0\end{pmatrix}$$

$$R_3=\begin{pmatrix}0&0&0&0\\0&0&1&0\\0&-1&0&0\\0&0&0&0\end{pmatrix}$$

In [15]:
R1 = N23
R2 = N31
R3 = N12

## Despliegue de los generadores

In [16]:
print('R1 ',R1)
print()
print('R2 ',R2)
print()
print('R3 ',R3)

R1  [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0. -1.  0.]]

R2  [[ 0.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  0.  0.]
 [ 0.  1.  0.  0.]]

R3  [[ 0.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  0.  0.]]


## Verificación del Álgebra

In [17]:
V3=conmutador(R1,R2)
V2=conmutador(R3,R1)
V1=conmutador(R2,R3)

In [18]:
print(V3+R3)
print()
print(V2+R2)
print()
print(V1+R1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


$$K_i\equiv{}J_{0i}$$

$$J_i=\frac{1}{2}\epsilon_{ijk}T_{jk}$$

$$J_1=T_{23}\,,\quad{}J_2=T_{31}\,,\quad{}J_3=T_{12}$$

# Generadores hermíticos de $so(1,3)$ 

* Los generadores $\mathbf{J}_{0j}$ ya se definieron como hermíticos.

#  $\mathbf{K}_i$

In [19]:
K1=J01
K2=J02
K3=J03
print(np.dot(R3,K1))

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.-1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


# $\mathbf{R}_i$ 

In [20]:
J1=1.j*R1
J2=1.j*R2
J3=1.j*R3

# Álgebra de Lie
$$
\begin{split}
[\mathbf{J}_{i},\mathbf{J}_{j}]&=-i\epsilon_{ijk}\mathbf{J}_{k}
\\
[\mathbf{K}_{i},\mathbf{K}_{j}]&=i\epsilon_{ijk}\mathbf{J}_{k}\\
%
[\mathbf{J}_{i},\mathbf{K}_{j}]&=-i\epsilon_{ijk}\mathbf{K}_{k}
\end{split}
$$

## Observaciones
* Como es de esperarse, los $\mathbf{J}_{i}$ constituyen una subálgebra de rotaciones 
* Con las redifiniciones que hemos introducido, $so(3)$ revela que el conmutador de dos boosts es una rotación, lo cuál tiene importantes consecuencias físicas (la precesión de Thomas es un ejemplo).
* Los boosts se comportan como vectores bajo rotaciones

---------------------------------------------------------------

## **Verificación del álgebra**

-------------------------------------------------------------------
$$
[\mathbf{J}_{i},\mathbf{J}_{j}]=-i\epsilon_{ijk}\mathbf{J}_{k}
$$

In [21]:
X3=conmutador(J1,J2)
X2=conmutador(J3,J1)
X1=conmutador(J2,J3)

print(X3+1.j*J3)
print()
print(X2+1.j*J2)
print()
print(X1+1.j*J1)

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


-------------------------------------------------------------------
$$
[\mathbf{K}_{i},\mathbf{K}_{j}]=i\epsilon_{ijk}\mathbf{J}_{k}
$$

In [22]:
Y3=conmutador(K1,K2)
Y2=conmutador(K3,K1)
Y1=conmutador(K2,K3) 

print(Y3-1.j*J3)
print()
print(Y2-1.j*J2)
print()
print(Y1-1.j*J1)
print()

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]



-------------------------------------------------------------------
$$
[\mathbf{J}_{i},\mathbf{K}_{j}]=-i\epsilon_{ijk}\mathbf{K}_{k}
$$

In [23]:
W3=conmutador(J1,K2)
W2=conmutador(J3,K1)
W1=conmutador(J2,K3)

print(W3+1.j*K3)
print()
print(W2+1.j*K2)
print()
print(W1+1.j*K1)

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


# Nueva Base del Álgebra

* Es conveniete introducir el siguiente cambio de base

$$
\begin{split}
\mathbf{N}_i=\frac{1}{2}(\mathbf{J}_i+i\mathbf{K}_i)\\
%
\mathbf{N}_i^\dagger=\frac{1}{2}(\mathbf{J}_i-i\mathbf{K}_i)
\end{split}
$$

## En esta nueva base:
* $so(1,3)$ toma la forma
$$
\begin{split}
[\mathbf{N}_i,\mathbf{N}_j]&=-i\epsilon_{ijk}\mathbf{N}_k\\
%
[\mathbf{N}^\dagger_i,\mathbf{N}_j]&=0\\
%
[\mathbf{N}^\dagger_i,\mathbf{N}^\dagger_j]&=-i\epsilon_{ijk}\mathbf{N}^\dagger_k\\
\end{split}
$$
* Interpretación: 
  * El álgebra se descompone como dos subálegebras $su(2)$ independietes.$$so(1,3)=su(2)\oplus{}su(2)$$
* Consecuencia: las representaciones pueden etiquetarse con los autovalores de los casimires: $A=\sum_i\,\mathbf{N}_i$, $B=\sum_i\mathbf{N}^\dagger_i\mathbf{N}^\dagger_i$
* Autovalores: $\ell_a(\ell_a+1)\,,\quad\ell_b(\ell_a+1)$. $\ell_a=0,1/2,1,3/2,...$ (igual para $\ell_b$) 
* La notación para las representaciones es: $(\ell_a,\ell_b)$

In [24]:
N1=(J1+1.j*K1)/2
N2=(J2+1.j*K2)/2
N3=(J3+1.j*K3)/2

DN1=(J1-1.j*K1)/2 #D por daga
DN2=(J2-1.j*K2)/2
DN3=(J3-1.j*K3)/2

In [25]:
Z3=conmutador(N1,N2)
Z2=conmutador(N3,N1)
Z1=conmutador(N2,N3)

print(Z3+1.j*N3)
print()
print(Z2+1.j*N2)
print()
print(Z1+1.j*N1)

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [26]:
DZ3=conmutador(DN1,DN2)
DZ2=conmutador(DN3,DN1)
DZ1=conmutador(DN2,DN3)

print(DZ3+1.j*DN3)
print()
print(DZ2+1.j*DN2)
print()
print(DZ1+1.j*DN1)

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [27]:
MZ3=conmutador(DN1,N2) # M por mixed
MZ2=conmutador(DN3,N1)
MZ1=conmutador(DN2,N3)

print(MZ3)
print()
print(MZ2)
print()
print(MZ1)

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


## Casimires de $so(1,3)$ en la representación fundamental

* Los autovalores de los casimires son $\ell_a=1/2$ y $\ell_b=1/2$
* Como consecuencia del estudio, podemos decir que la representación **4** ó **vectorial** de $so(1,3)$ es la $(1/2,1/2)$

In [28]:
A=N1*N1+N2*N2+N3*N3
B=DN1*DN1+DN2*DN2+DN3*DN3

In [29]:
print('Primer Casimir',A)

print('Segundo Casimir',B)

Primer Casimir [[0.75+0.j 0.  +0.j 0.  +0.j 0.  +0.j]
 [0.  +0.j 0.75+0.j 0.  +0.j 0.  +0.j]
 [0.  +0.j 0.  +0.j 0.75+0.j 0.  +0.j]
 [0.  +0.j 0.  +0.j 0.  +0.j 0.75+0.j]]
Segundo Casimir [[0.75+0.j 0.  +0.j 0.  +0.j 0.  +0.j]
 [0.  +0.j 0.75+0.j 0.  +0.j 0.  +0.j]
 [0.  +0.j 0.  +0.j 0.75+0.j 0.  +0.j]
 [0.  +0.j 0.  +0.j 0.  +0.j 0.75+0.j]]
